version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mobile_subscription_system
      MYSQL_USER: mUser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    restart: always
  spring-boot-rest-api-app:
    container_name: mobile_subscription
    image: mobile-subscription-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: mUser
      DATABASE_PASSWORD: password
      DATABASE_NAME: mobile_subscription_system
      DATABASE_PORT: 3306
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
    depends_on:
      - mysql